version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:7777"

  nginx:
    image: nginx
    ports:
      - "80:80"
    links:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf